export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const USER_LOADED = 'USER_LOADED';

// songs
export const USER_SONGS_LOADED = 'USER_SONGS_LOADED';
export const USER_SONGS_LOAD_FAIL = 'USER_SONGS_LOAD_FAIL';
export const SONG_PLAYED = 'SONG_PLAYED'
export const SONG_PLAYED_FAIL = 'SONG_PLAYED_FAIL';
export const SONG_SKIPPED = 'SONG_SKIPPED';
export const SONG_SKIPPED_FAIL = 'SONG_SKIPPED_FAIL';
export const SONG_LIKED = 'SONG_LIKED';
export const SONG_LIKED_FAIL = 'SONG_LIKED_FAIL';
export const SONG_DISLIKED = 'SONG_DISLIKED';
export const SONG_DISLIKED_FAIL = 'SONG_DISLIKED_FAIL';


export const PLAYLIST_CREATED ='PLAYLIST_CREATED';
export const PLAYLIST_CLEARED ='PLAYLIST_CLEARED';
export const PLAYLIST_UPDATED ='PLAYLIST_UPDATED';

export const USER_SONG_PLAYED = 'USER_SONG_PLAYED';
export const CLEAR_USER_PLAYING_SONGS = 'CLEAR_USER_PLAYING_SONGS';