export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const USER_LOADED = 'USER_LOADED';

// songs
export const USER_SONGS_LOADED = 'USER_SONGS_LOADED';
export const USER_SONGS_LOAD_FAIL = 'USER_SONGS_LOAD_FAIL';
export const SONG_PLAYED = 'SONG_PLAYED'
export const SONG_PLAYED_FAIL = 'SONG_PLAYED_FAIL';
export const SONG_SKIPPED = 'SONG_SKIPPED';
export const SONG_SKIPPED_FAIL = 'SONG_SKIPPED_FAIL';